name = "cf-ai-draw"
main = "worker.js"
compatibility_date = "2024-01-01"

[site]
bucket = "/"

[build]
command = ""

# 开发环境配置
[env.dev]
name = "cf-ai-draw-dev"
workers_dev = true

[env.preview]
name = "cf-ai-draw-preview"

# 生产环境配置
[env.production]
name = "cf-ai-draw"
